### ISSUE TITLE
Switch to an actively maintained golang Matrix math library

### ISSUE THREAD

**Issue by vibbix** [stevenmiller888/go-mind#3]
As of right now, github.com/skelterjohn/go.matrix hasn't had an update since May 17th, 2013. I propose switching from go.matrix to github.com/gonum/matrix which is still being actively updated.

**Comment by stevenmiller888** [comment]
:+1: Great idea. I'll get to this as soon as I can. Otherwise I'm fully open to PRs

**Comment by vibbix** [comment]
I'm adding up some examples for now, I'll push that in a PR in a little bit. I might get some work started on moving it over!

**Comment by stevenmiller888** [comment]
It's super ugly but I have everything working on the [switch-to-mat64](https://github.com/stevenmiller888/go-mind/tree/switch-to-mat64) branch :tada:

**Comment by stevenmiller888** [comment]
@vibbix would love to get your thoughts on the updates in that branch if you get some time!

**Comment by vibbix** [comment]
Just came back from a weekend off. Just compared your fork against mine. Except for some minor differences, your implementations are virtually identical. However I had a few bugs in mine, so i'm gonna open a debug fork to get percent error between the two libraries, to make sure all numbers match(I'll use either a sin function or a PRNG to simulate random numbers), and i'll send back the results.

**Comment by stevenmiller888** [comment]
Sounds good man!

**Comment by vibbix** [comment]
Alright, I just used a normalized sin function, and was able to get identical results on the tests I ran, so I believe at this point the branches can be merged, unless you want a more complete implementation for testing.

**Comment by stevenmiller888** [comment]
Badass, let's go ahead and merge it. Thanks for running those tests.
